import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  const [scroll, setScroll] = useState(0);

  useEffect(() => {
    let progressBarHandler = () => {
      const totalScroll = document.documentElement.scrollTop;
      const windowHeight =
        document.documentElement.scrollHeight -
        document.documentElement.clientHeight;
      const scroll = `${totalScroll / windowHeight}`;

      setScroll(scroll);
    };

    window.addEventListener("scroll", progressBarHandler);

    return () => window.removeEventListener("scroll", progressBarHandler);
  });

  return (
    <>
      <div className={styles.containerr}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script src="sc.js"></script>
        </Head>
        <div className="">
          <div id="progressBarContainer">
            <div
              id="progressBar"
              style={{ transform: `scale(${scroll}, 1)`, opacity: 1 }}
            />
          </div>

          <div>
            <div className={`${styles.row} ${styles.marginTop} `}>
              <div className="">
                <div className=" d-lg-block d-md-block d-sm-block d-flex">
                  <div className="">
                    <h1 className={styles.heading}>It’s Asim Naveed,</h1>
                    <h1 className={styles.heading1}>
                      An Entrepreneur & Investor.
                    </h1>
                  </div>
                  <div className="d-lg-none d-md-none d-sm-none d-block mt-4 ms-2">
                    <Image
                      src="/Pitch Your Idea.PNG.png"
                      width="88"
                      height="88"
                    ></Image>
                  </div>
                </div>
                <p className={styles.heroPera}>
                  Since 2011, I support and assist my clients in execution and
                  management of projects. Further I advice them in various
                  project-relevant agendas. Added I take responsibility for both
                  operational and strategic Project Management.
                </p>
              </div>
              <div className=" col-xl-3 col-lg-2 col-md-2 col-sm-2 col-2 d-lg-flex d-md-flex d-sm-flex d-none flex-column-reverse align-items-end order-lg-1 order-md-1 order-sm-1 order-0">
                <Image
                  src="/Pitch Your Idea.PNG.png"
                  width="132"
                  height="132"
                ></Image>
              </div>
            </div>
          </div>

          <div className={styles.marginTop}>
            <div className="row justify-content-between">
              <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                <h1 className=" text-success">01</h1>
                <p className={styles.rev_block}>Recrutability</p>
                <h1
                  className={`${styles.rev_block} `}
                  style={{ color: "#082009", marginTop: "2rem" }}
                >
                  Portfolio Platform
                </h1>

                <p
                  className={`${styles.rev_block} ${styles.margin}`}
                  style={{ width: "50%" }}
                >
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Vestibulum ut feugiat nulla. Pellentesque a efficitur quam.
                  Proin eu lobortis augue.
                </p>
              </div>
              <div className="col-lg-4 col-md-4 col-sm-12 col-12 ">
                <div className="frame"></div>
              </div>
            </div>
          </div>

          <div className={styles.marginTop}>
            <div className="row justify-content-between">
              <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                <h1 className={`" text-success  " `}>
                  {/* <h1 className={`" text-success  " ${styles.rev_block} `}> */}
                  02
                </h1>
                <p className={styles.rev_block}>Recrutability</p>
                <h1
                  className={`${styles.rev_block} `}
                  style={{ color: "#082009", marginTop: "2rem" }}
                >
                  Portfolio Platform
                </h1>

                <p
                  className={`${styles.rev_block} ${styles.margin}`}
                  style={{ width: "50%" }}
                >
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Vestibulum ut feugiat nulla. Pellentesque a efficitur quam.
                  Proin eu lobortis augue.
                </p>
              </div>
              <div className="col-lg-4 col-md-4 col-sm-12 col-12 ">
                <div className=""></div>
              </div>
            </div>
          </div>
        </div>
        {/* footer */}
      </div>
      {/* <div className={styles.marginTop}>
<div class="text-center footerbg">
    <h1 class="display-5 fw-bold">Got an idea? I am open to meet creative minds and collaborations. </h1> 
    <div class="mt-5">
      <p class="footerHeading px-4 mb-5">Got an idea? I am open to meet creative minds and collaborations. </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mt-5">
        <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Primary button</button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button>
      </div>
    </div>
  </div>
</div> */}

      <div className={styles.marginTopFoo}>
        <div class="text-secondary px-4 py-5 text-center footerbg">
          <div class="py-5">
            {/* <h1 class="display-5 fw-bold text-white">Dark mode hero</h1> */}
            <div class="col-lg-6 mx-auto">
              <p class="footerHeading px-4 mb-5 tColor">
                Got an idea? I am open to meet creative minds and
                collaborations.{" "}
              </p>
              <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <button
                  type="button"
                  class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold"
                >
                  Custom button
                </button>
                <button type="button" class="btn btn-outline-light btn-lg px-4">
                  Secondary
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
